spring.application.name=todos-buscando

# MongoDB Atlas
spring.data.mongodb.uri=mongodb://localhost:27017/todosbuscando

# Email (Gmail) — cambiá por tus datos
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=todosbuscandoapp@gmail.com
spring.mail.password=oorfecrldlbvqgbo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Auto-crear índices de MongoDB al arrancar
spring.data.mongodb.auto-index-creation=true

# CORS
server.port=${SERVER_PORT:8080}

# Redis (caché)
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
# TTL del caché de alertas activas en segundos (5 minutos)
alerta.cache.ttl-segundos=60

# Neo4j
spring.neo4j.uri=${SPRING_NEO4J_URI:bolt://localhost:7687}
spring.neo4j.authentication.username=${SPRING_NEO4J_AUTHENTICATION_USERNAME:neo4j}
spring.neo4j.authentication.password=${SPRING_NEO4J_AUTHENTICATION_PASSWORD:todos1234}

# API externa de personas desaparecidas (argly.com.ar / SIFEBU)
alerta.api.externa.url=https://api.argly.com.ar/v1/personas-desaparecidas
alerta.api.externa.intervalo-ms=600000
